name: pages build and deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Taipei'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.135.0'

    - name: Build
      run: |
        hugo version
        hugo --minify
        ls -R public

    - name: Debug info
      run: |
        pwd
        ls -la
        git status

    - name: Check public directory
      run: |
        ls -R public
        cat public/index.html || echo "index.html not found"

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages